### ISSUE TITLE
parseOptions regex misses legitimate folder paths

### ISSUE THREAD

**Issue by scottclayton** [SylverFox/smb-enumerate-files#1]
@SylverFox 
Neat package—speedy and quite elegant!

A heads-up that the `smbUrlRe` regex in its current form can't handle a folder like `'Backups 2019-07-21'`, even though it's a valid folder name in Windows

I'm not a regex master, so I can't recommend anything in particular. I worked around it for my purposes at over here, but I wouldn't necessarily endorse it:
https://github.com/scottclayton/smb-enumerate-files/commit/be198723e9dd50c6b53d4e90ed668defabf97dfe

**Comment by SylverFox** [comment]
> Neat package—speedy and quite elegant!

Thanks! Happy to hear from you.

The regex does indeed not include special characters on the folder. I've updated the regex to be more lenient. It should work for you now.
