### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 24. Received 32

### ISSUE THREAD

**Issue by pierrejochem** [SylverFox/smb-enumerate-files#2]
This error occurs when using node version 14.

Error is in line 220

https://github.com/SylverFox/smb-enumerate-files/blob/6dee695cb2356c4b600ef5e717e253820625aa35/index.js#L220

Lenght is 32 but needs shorter then 24

**Comment by SylverFox** [comment]
Thanks for the report! And sorry it took so long for me to get around to look at it.
The bug is fixed with 1224bef7049485d5da0431caa0977a05c5d1e534

**Comment by pierrejochem** [comment]
Thank you @SylverFox  :-)
